"""Vocabulary: each tuple is a word group; the first entry is the group name.

Room logic matches on group names, so "l", "look" and "examine" are all
the word "look". Words in IGNORE are dropped before matching, as AGI did.
"""

IGNORE = frozenset("the a an at to in into on onto of with for up my some this that please and then game".split())

GROUPS: list[tuple[str, ...]] = [
    # verbs
    ("look", "l", "examine", "see", "view", "inspect", "read", "x", "watch"),
    ("get", "take", "pick", "grab", "acquire"),
    ("drop", "leave", "discard", "throw"),
    ("open", "unlock"),
    ("close", "shut"),
    ("talk", "speak", "chat", "converse", "ask", "say", "tell", "hello", "hi"),
    ("buy", "purchase", "order"),
    ("give", "offer", "hand"),
    ("use",),
    ("drink", "sip", "swig", "chug"),
    ("eat", "chew"),
    ("push", "press", "hit", "punch"),
    ("draw",),
    ("bet", "wager", "gamble", "stake"),
    ("pull", "tug"),
    ("sit", "rest"),
    ("stand",),
    ("wait", "z"),
    ("kiss", "hug", "smooch"),
    ("dance", "boogie"),
    ("enter", "go", "walk", "climb", "exit", "drive", "ride"),
    ("inventory", "i", "inv"),
    ("help", "hint"),
    ("quit", "q", "bye"),
    ("save",),
    ("restore", "load"),
    ("restart",),
    ("score",),
    ("smell", "sniff"),
    ("listen", "hear"),
    ("kick",),
    ("knock", "rap", "bang"),
    ("play", "flip"),
    ("pay", "tip"),
    ("call", "dial", "hail", "whistle", "wave", "flag"),
    ("search", "rummage", "dig", "check"),
    ("pet", "pat", "stroke", "touch"),
    # directions
    ("north", "n", "forward"),
    ("south", "s", "back", "backward"),
    ("east", "e", "right"),
    ("west", "w", "left"),
    # nouns: the world
    ("self", "me", "myself", "paul", "suit", "pants", "clothes"),
    ("room", "around", "here", "place"),
    ("door", "doorway", "entrance"),
    ("wall", "walls"),
    ("floor", "ground", "sidewalk", "pavement", "street"),
    ("sign", "neon", "lights", "light"),
    ("window", "windows"),
    ("bar", "counter"),
    ("bartender", "barkeep", "barman", "keeper"),
    ("drunk", "bum", "man", "guy", "lush", "wino", "customer"),
    ("dog", "mutt", "hound"),
    ("stool", "stools", "chair", "seat", "booth", "table"),
    ("whiskey", "whisky", "booze", "liquor", "shot", "beer", "scotch", "bourbon"),
    ("remote", "control", "clicker"),
    ("money", "cash", "dollars", "dollar", "bucks", "wallet"),
    ("jukebox", "music", "juke"),
    ("bathroom", "restroom", "toilet", "john", "men", "mens", "ladies", "womens"),
    ("trash", "garbage", "can", "bin", "dumpster"),
    ("hydrant",),
    ("building", "buildings", "bar_building", "dive"),
    ("cab", "taxi", "car"),
    ("driver", "cabbie", "cabby", "chauffeur"),
    ("out",),
    ("meter",),
    ("dashboard", "dash", "windshield", "radio"),
    ("casino", "gambling"),
    ("disco", "club", "nightclub"),
    ("store", "shop", "market"),
    ("chapel", "church", "wedding"),
    ("alley", "alleyway"),
    ("phone", "telephone", "payphone", "receiver"),
    ("clerk", "cashier", "shopkeeper", "attendant", "kid"),
    ("wine", "bottle", "vino", "plonk"),
    ("magazine", "mag", "periodical"),
    ("shelf", "shelves", "aisle", "aisles", "rack", "goods", "stuff", "snacks"),
    ("cooler", "fridge", "refrigerator"),
    ("newspaper", "paper", "news"),
    ("steal", "shoplift", "swipe", "pocket", "nick"),
    ("time",),
    ("pass", "card", "membership", "ticket"),
    ("rope", "velvet", "line"),
    ("ball", "mirrorball", "glitterball"),
    ("dj", "deejay"),
    ("song", "tune", "request", "record"),
    ("ring", "diamond", "jewelry"),
    ("slot", "slots", "machine", "machines", "lever", "handle", "reels"),
    ("blackjack", "cards", "twentyone", "deck"),
    ("dealer", "croupier", "pit", "boss", "security"),
    ("chip", "chips", "tokens", "winnings"),
    ("prize", "prizes", "case", "gift", "gifts", "jewellery"),
    ("elevator", "lift"),
    ("lounge", "comedian", "comic", "comedy"),
    ("cashout", "collect"),
    ("preacher", "priest", "minister", "reverend", "pastor", "father", "vicar"),
    ("marry", "wed", "propose", "elope"),
    ("altar",),
    ("pew", "pews", "bench", "benches"),
    ("organ", "organist", "piano"),
    ("bell",),
    ("glass", "stained"),
    ("collection", "donation", "plate", "offering", "tithe"),
    ("key", "keys"),
    ("veil",),
    ("untie", "struggle", "wriggle", "escape", "free", "loosen"),
    ("scream", "shout", "yell", "holler"),
    ("note", "letter"),
    ("champagne", "bucket", "bubbly"),
    ("balcony", "roof", "pool", "terrace", "rail", "railing", "parapet", "edge", "ledge"),
    ("maid", "housekeeping", "housekeeper", "desk"),
    ("coffee", "cup", "espresso", "latte"),
    ("apple", "fruit", "bowl"),
    ("tub", "hottub", "jacuzzi", "spa", "bath"),
    ("stage", "microphone", "mic", "curtain"),
    ("joke", "jokes", "act", "routine"),
    ("heckle", "boo", "laugh", "clap", "applaud"),
    ("plant", "palm", "fern"),
    ("swim", "bathe", "soak"),
    ("rose", "flower", "flowers"),
    ("puddle", "puddles", "water"),
    ("password", "secret"),
    ("graffiti", "writing", "scrawl", "scrawls", "words", "message", "messages"),
    ("sink", "basin", "faucet", "tap"),
    ("mirror", "reflection", "ceiling"),
    ("photo", "photograph", "picture", "frame"),
    ("lottery", "scratcher", "scratchcard", "lotto"),
    ("scratch", "rub"),
    ("urinal",),
    ("cigarette", "butt", "smoke"),
    ("soap",),
    ("flush",),
    ("wash", "clean", "rinse"),
    ("hands", "face", "hair"),
    ("rooster", "roosters"),
    ("sent",),
    (
        "hooker",
        "prostitute",
        "woman",
        "lady",
        "girl",
        "dolores",
        "ginger",
        "redhead",
        "her",
        "she",
        "babe",
        "date",
        "bride",
        "wife",
        "hope",
        "receptionist",
        "secretary",
        "dawn",
    ),
    ("candy", "chocolate", "chocolates", "box", "sweets", "bonbons"),
    ("bed", "mattress", "sheets", "pillow"),
    ("nightstand", "dresser", "lamp", "bedside"),
    ("rug", "carpet"),
    ("heart",),
    ("protection", "condom", "rubber", "prophylactic"),
    ("love", "sex", "woo", "seduce", "romance"),
    ("undress", "strip"),
    ("bouncer", "brick", "pimp", "thug", "goon", "mister", "mr", "doorman"),
    ("tv", "television", "set", "screen"),
    ("couch", "sofa", "cushion", "cushions"),
    ("stairs", "staircase", "steps", "stairway", "upstairs"),
    ("crate",),
    ("channel", "channels", "show", "program"),
    ("change", "switch", "turn", "click"),
]

# Pauline's game mirrors the cast, so the gendered words change sides: "man"
# is the one she's chasing and "lady" is the drunk in the booth. Each entry
# replaces the group of the same name; room logic never sees the difference.
PAULINE_GROUPS: list[tuple[str, ...]] = [
    ("self", "me", "myself", "pauline", "suit", "pantsuit", "pants", "clothes"),
    ("bartender", "barkeep", "barmaid", "keeper"),
    ("drunk", "bum", "woman", "lady", "gal", "lush", "wino", "customer"),
    ("preacher", "priest", "priestess", "minister", "reverend", "pastor", "mother", "vicar"),
    ("maid", "housekeeping", "housekeeper", "houseman", "porter", "desk"),
    ("urinal", "dispenser", "vending"),
    ("lounge", "comedian", "comedienne", "comic", "comedy"),
    (
        "hooker",
        "gigolo",
        "prostitute",
        "man",
        "guy",
        "boy",
        "donny",
        "rusty",
        "redhead",
        "him",
        "he",
        "hunk",
        "date",
        "groom",
        "husband",
        "chance",
        "receptionist",
        "secretary",
        "dusty",
    ),
    ("bouncer", "roxy", "madam", "thug", "goon", "miss", "ms", "doorman", "doorwoman"),
]

ANY = "anyword"
ROL = "rol"  # rest of line


def _build(groups: list[tuple[str, ...]]) -> dict[str, str]:
    table: dict[str, str] = {}
    for group in groups:
        name = group[0]
        for word in group:
            assert word not in table, f"duplicate vocabulary word: {word}"
            table[word] = name
    return table


def _mirrored() -> list[tuple[str, ...]]:
    swaps = {group[0]: group for group in PAULINE_GROUPS}
    assert swaps.keys() <= {group[0] for group in GROUPS}, "PAULINE_GROUPS may only replace existing groups"
    return [swaps.get(group[0], group) for group in GROUPS]


LOOKUP: dict[str, str] = _build(GROUPS)
PAULINE_LOOKUP: dict[str, str] = _build(_mirrored())


def lookup(pauline: bool = False) -> dict[str, str]:
    return PAULINE_LOOKUP if pauline else LOOKUP
